// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Cache is an autogenerated mock type for the Cache type
type Cache struct {
	mock.Mock
}

// CollectSwiftPackages provides a mock function with given fields: projectPath
func (_m *Cache) CollectSwiftPackages(projectPath string) error {
	ret := _m.Called(projectPath)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(projectPath)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SwiftPackagesPath provides a mock function with given fields: projectPth
func (_m *Cache) SwiftPackagesPath(projectPth string) (string, error) {
	ret := _m.Called(projectPth)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(projectPth)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(projectPth)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
