// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import (
	version "github.com/hashicorp/go-version"
	mock "github.com/stretchr/testify/mock"
)

// RunnerDependencyInstaller is an autogenerated mock type for the DependencyInstaller type
type RunnerDependencyInstaller struct {
	mock.Mock
}

// Install provides a mock function with given fields:
func (_m *RunnerDependencyInstaller) CheckInstall() (*version.Version, error) {
	ret := _m.Called()

	var r0 *version.Version
	if rf, ok := ret.Get(0).(func() *version.Version); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*version.Version)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewRunnerDependencyInstaller interface {
	mock.TestingT
	Cleanup(func())
}

// NewRunnerDependencyInstaller creates a new instance of RunnerDependencyInstaller. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRunnerDependencyInstaller(t mockConstructorTestingTNewRunnerDependencyInstaller) *RunnerDependencyInstaller {
	mock := &RunnerDependencyInstaller{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
