// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// PathChecker is an autogenerated mock type for the PathChecker type
type PathChecker struct {
	mock.Mock
}

// IsDirExists provides a mock function with given fields: pth
func (_m *PathChecker) IsDirExists(pth string) (bool, error) {
	ret := _m.Called(pth)

	if len(ret) == 0 {
		panic("no return value specified for IsDirExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return rf(pth)
	}
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(pth)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(pth)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsPathExists provides a mock function with given fields: pth
func (_m *PathChecker) IsPathExists(pth string) (bool, error) {
	ret := _m.Called(pth)

	if len(ret) == 0 {
		panic("no return value specified for IsPathExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return rf(pth)
	}
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(pth)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(pth)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPathChecker creates a new instance of PathChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPathChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *PathChecker {
	mock := &PathChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
