// Code generated by mockery v2.30.16. DO NOT EDIT.

package mocks

import (
	xcodeversion "github.com/bitrise-io/go-xcode/v2/xcodeversion"
	mock "github.com/stretchr/testify/mock"
)

// XcodeVersionProvider is an autogenerated mock type for the Reader type
type XcodeVersionProvider struct {
	mock.Mock
}

// GetVersion provides a mock function with given fields:
func (_m *XcodeVersionProvider) GetVersion() (xcodeversion.Version, error) {
	ret := _m.Called()

	var r0 xcodeversion.Version
	var r1 error
	if rf, ok := ret.Get(0).(func() (xcodeversion.Version, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() xcodeversion.Version); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(xcodeversion.Version)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewXcodeVersionProvider creates a new instance of XcodeVersionProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewXcodeVersionProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *XcodeVersionProvider {
	mock := &XcodeVersionProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
