// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	simulator "github.com/bitrise-steplib/steps-xcode-test/simulator"
	mock "github.com/stretchr/testify/mock"
)

// Simulator is an autogenerated mock type for the Simulator type
type Simulator struct {
	mock.Mock
}

// GetLatestSimulatorInfoAndVersion provides a mock function with given fields: osName, deviceName
func (_m *Simulator) GetLatestSimulatorInfoAndVersion(osName string, deviceName string) (simulator.Info, string, error) {
	ret := _m.Called(osName, deviceName)

	var r0 simulator.Info
	if rf, ok := ret.Get(0).(func(string, string) simulator.Info); ok {
		r0 = rf(osName, deviceName)
	} else {
		r0 = ret.Get(0).(simulator.Info)
	}

	var r1 string
	if rf, ok := ret.Get(1).(func(string, string) string); ok {
		r1 = rf(osName, deviceName)
	} else {
		r1 = ret.Get(1).(string)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(string, string) error); ok {
		r2 = rf(osName, deviceName)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetSimulatorInfo provides a mock function with given fields: osNameAndVersion, deviceName
func (_m *Simulator) GetSimulatorInfo(osNameAndVersion string, deviceName string) (simulator.Info, error) {
	ret := _m.Called(osNameAndVersion, deviceName)

	var r0 simulator.Info
	if rf, ok := ret.Get(0).(func(string, string) simulator.Info); ok {
		r0 = rf(osNameAndVersion, deviceName)
	} else {
		r0 = ret.Get(0).(simulator.Info)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(osNameAndVersion, deviceName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LaunchSimulator provides a mock function with given fields: simulatorID, xcodebuildMajorVersion
func (_m *Simulator) LaunchSimulator(simulatorID string, xcodebuildMajorVersion int) error {
	ret := _m.Called(simulatorID, xcodebuildMajorVersion)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, int) error); ok {
		r0 = rf(simulatorID, xcodebuildMajorVersion)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ResetLaunchServices provides a mock function with given fields:
func (_m *Simulator) ResetLaunchServices() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SimulatorBoot provides a mock function with given fields: id
func (_m *Simulator) SimulatorBoot(id string) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SimulatorCollectDiagnostics provides a mock function with given fields:
func (_m *Simulator) SimulatorCollectDiagnostics() (string, error) {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SimulatorDiagnosticsName provides a mock function with given fields:
func (_m *Simulator) SimulatorDiagnosticsName() (string, error) {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SimulatorEnableVerboseLog provides a mock function with given fields: id
func (_m *Simulator) SimulatorEnableVerboseLog(id string) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SimulatorShutdown provides a mock function with given fields: id
func (_m *Simulator) SimulatorShutdown(id string) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
