// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Exporter is an autogenerated mock type for the Exporter type
type Exporter struct {
	mock.Mock
}

// ExportSimulatorDiagnostics provides a mock function with given fields: deployDir, pth, name
func (_m *Exporter) ExportSimulatorDiagnostics(deployDir string, pth string, name string) {
	_m.Called(deployDir, pth, name)
}

// ExportTestRunResult provides a mock function with given fields: failed
func (_m *Exporter) ExportTestRunResult(failed bool) {
	_m.Called(failed)
}

// ExportUITestArtifacts provides a mock function with given fields: xcResultPath, scheme
func (_m *Exporter) ExportUITestArtifacts(xcResultPath string, scheme string) {
	_m.Called(xcResultPath, scheme)
}

// ExportXCResultBundle provides a mock function with given fields: deployDir, xcResultPath, scheme
func (_m *Exporter) ExportXCResultBundle(deployDir string, xcResultPath string, scheme string) {
	_m.Called(deployDir, xcResultPath, scheme)
}

// ExportXcodebuildBuildLog provides a mock function with given fields: deployDir, xcodebuildBuildLog
func (_m *Exporter) ExportXcodebuildBuildLog(deployDir string, xcodebuildBuildLog string) {
	_m.Called(deployDir, xcodebuildBuildLog)
}

// ExportXcodebuildTestLog provides a mock function with given fields: deployDir, xcodebuildTestLog
func (_m *Exporter) ExportXcodebuildTestLog(deployDir string, xcodebuildTestLog string) {
	_m.Called(deployDir, xcodebuildTestLog)
}
